# Generated by Django 4.1.1 on 2023-05-16 09:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('business', models.CharField(blank=True, max_length=200, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('contact', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('issued', models.DateField()),
                ('description', models.CharField(max_length=100)),
                ('total_exc', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_gst', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_inc', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('purpose', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.customer')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('is_person', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TimeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=100, unique=True)),
                ('date_of', models.DateField(default=datetime.date(2023, 5, 16))),
                ('started', models.DateTimeField()),
                ('ended', models.DateTimeField()),
                ('hrs', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bill_at', models.CharField(default='h', max_length=2)),
                ('bill', models.BooleanField(default=True)),
                ('total_exc', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_gst', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_inc', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.invoice')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.job')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.resource')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.job'),
        ),
        migrations.CreateModel(
            name='BillingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('billing_per', models.CharField(choices=[('h', 'Hour'), ('d', 'Day')], default='h', max_length=2)),
                ('active', models.BooleanField(default=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.job')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.resource')),
            ],
        ),
    ]
