# Generated by Django 4.1.1 on 2023-05-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_alter_timeitem_date_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='issued',
            field=models.DateField(blank=True, null=True),
        ),
    ]
