# Generated by Django 4.1.1 on 2024-01-23 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('la', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='MasterList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('purpose', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('disabled', models.BooleanField(default=False)),
                ('is_master', models.BooleanField(default=False)),
                ('leaders', models.ManyToManyField(blank=True, related_name='master_leader_of', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='master_manage_by', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, related_name='master_member_of', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MasterItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('quantity_plan', models.CharField(blank=True, default='1', max_length=30, null=True)),
                ('quantity_actual', models.CharField(blank=True, default='1', max_length=30, null=True)),
                ('confirmed', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('I', 'Disregard')], default='No', max_length=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='la.mastercategories')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='la.masterlist')),
            ],
            options={
                'ordering': ['category', 'description'],
            },
        ),
        migrations.AddField(
            model_name='mastercategories',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='la.masterlist'),
        ),
    ]
